name: Generate Signed Profile Picture URLs (Daily)

on:
  schedule:
    - cron: '0 3 * * *'  # ogni giorno alle 03:00 UTC
  workflow_dispatch:      # permette anche l'esecuzione manuale

jobs:
  generate-signed-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          response=$(curl -s -w "%{http_code}" -o output.txt -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/signed_pic_url" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}")

          echo "HTTP Status: $response"
          echo "Response body:"
          cat output.txt

          if [ "$response" -ne 200 ]; then
            exit 1
          fi

